version: '3.8'

services:
  app:
    image: app-dev
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - POSTGRES_DATABASE_URI=postgresql://username:password@postgres:5432/questionsdb
      
  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
  postgres:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=questionsdb
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
